apiVersion: v1
kind: Service
metadata:
  #name: {{ include "keycloak-service.fullname" . }}
  name: "sbrc-registry-keycloak"
  namespace: {{ .Release.Namespace }}
  annotations:
{{ toYaml .Values.ServiceAnnotations | indent 4 }}
    service.beta.kubernetes.io/aws-load-balancer-name: sbrc-keycloak-ui
  labels:
    {{- include "keycloak-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "keycloak-service.selectorLabels" . | nindent 4 }}
    #eks.amazonaws.com/fargate-profile: {{ .Release.Namespace }}
